# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poke_number',
            field=models.IntegerField(default=0),
        ),
    ]
