# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180228_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='poked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poked_me', to='users.User'),
            preserve_default=False,
        ),
    ]
