# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180228_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_me', to='users.User')),
            ],
        ),
    ]
