# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_pokes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pokes',
            field=models.IntegerField(default=0),
        ),
    ]
