# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_pokes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked_by',
        ),
        migrations.AddField(
            model_name='poke',
            name='poked_by',
            field=models.ManyToManyField(related_name='poked_me', to='users.User'),
        ),
    ]
