# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_poke_pokes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pokes',
        ),
    ]
