# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180228_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pokes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poke',
            name='poked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_me', to='users.User'),
        ),
    ]
